### ISSUE TITLE
Could you please tell me how to fix this issue

### ISSUE THREAD

**Issue by JianfengNing** [zongyi-li/graph-pde#3]
Traceback (most recent call last):
  File "D:/Desktop/fourier_neural_operator-master/fourier_neural_operator-master/fourier_1d.py", line 160, in <module>
    dataloader = MatReader('data/burgers_data_R10.mat')
  File "D:\Desktop\fourier_neural_operator-master\fourier_neural_operator-master\utilities3.py", line 31, in __init__
    self._load_file()
  File "D:\Desktop\fourier_neural_operator-master\fourier_neural_operator-master\utilities3.py", line 38, in _load_file
    self.data = h5py.File(self.file_path)
  File "D:\Users\FIVE\miniconda3\envs\pytorch\lib\site-packages\h5py\_hl\files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "D:\Users\FIVE\miniconda3\envs\pytorch\lib\site-packages\h5py\_hl\files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'data/burgers_data_R10.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Process finished with exit code 1

**Comment by zongyi-li** [comment]
It says "No such file or directory".  Have you downloaded the dataset and put it under 'data/burgers_data_R10.mat' ?

**Comment by xjtu-YiranMeng** [comment]
Hello！ Sorry to bother you. I am a PHD student and learning your GKN nowadays. I have trouble in understanding the relationship between from UAI1 to UAI8. 
1.  UAI1, UAI2, UAI3 ,..., UAI8 are all combine together to solve a PDE  problem 
2.  UAI1, UAI2, UAI3 ,..., UAI8 are different ways （maybe 8 different ways） to solve the same PDE problem
which one is right ?
And I wonder the specific PDE is？
I am looking forward for your response
